language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services: 
  - sqlite
  - postgres
  - mysql

env:
  - DJANGO=1.8 DB=sqlite
  - DJANGO=1.8 DB=postgres
  - DJANGO=1.8 DB=mysql
  - DJANGO=1.9 DB=sqlite
  - DJANGO=1.9 DB=postgres
  - DJANGO=1.9 DB=mysql
  - DJANGO=1.10 DB=sqlite
  - DJANGO=1.10 DB=postgres
  - DJANGO=1.10 DB=mysql
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=postgres
  - DJANGO=1.11 DB=mysql

matrix:
  exclude:
    - python: "3.6"
      env: DJANGO=1.8 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.8 DB=mysql
    - python: "3.6"
      env: DJANGO=1.8 DB=postgres

    - python: "3.3"
      env: DJANGO=1.9 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.9 DB=mysql
    - python: "3.3"
      env: DJANGO=1.9 DB=postgres
    - python: "3.6"
      env: DJANGO=1.9 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.9 DB=mysql
    - python: "3.6"
      env: DJANGO=1.9 DB=postgres

    - python: "3.3"
      env: DJANGO=1.10 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.10 DB=postgres
    - python: "3.3"
      env: DJANGO=1.10 DB=mysql
    - python: "3.6"
      env: DJANGO=1.10 DB=sqlite
    - python: "3.6"
      env: DJANGO=1.10 DB=postgres
    - python: "3.6"
      env: DJANGO=1.10 DB=mysql

    - python: "3.3"
      env: DJANGO=1.11 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.11 DB=postgres
    - python: "3.3"
      env: DJANGO=1.11 DB=mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python manage.py test

# deploy:
#   provider: pages
#   local_dir: "./output"
#   skip_cleanup: true
#   github_token: $GH_TOKEN # Set in travis-ci.org dashboard
#   target_branch: 
#   on:
#     branch: master

notifications:
  email:
    on_success: change
    on_failure: change