language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services: 
  - sqlite
  - postgres
  - mysql

env:
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=postgres
  - DJANGO=1.11 DB=mysql
  - DJANGO=2.0 DB=sqlite
  - DJANGO=2.0 DB=postgres
  - DJANGO=2.0 DB=mysql

matrix:
  # fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=flake8
  exclude:
    - python: "3.3"
      env: DJANGO=1.11 DB=sqlite
    - python: "3.3"
      env: DJANGO=1.11 DB=postgres
    - python: "3.3"
      env: DJANGO=1.11 DB=mysql
    - python: "3.3"
      env: DJANGO=2.0 DB=sqlite
    - python: "3.3"
      env: DJANGO=2.0 DB=postgres
    - python: "3.3"
      env: DJANGO=2.0 DB=mysql

  # allow_failures:

before_install:
  - pip install -q 'flake8<3'
  - PYFLAKES_NODOCTEST=1 flake8 tasklist

install:
  # - pip install -r requirements.txt
  - PYTHON=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'`
  - if [[ $DB == mysql ]] && [[ ${PYTHON:0:1} == "2" ]]; then pip install -q mysql-python; elif [[ $DB == mysql ]] && [[ ${PYTHON:0:1} == "3" ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  # - pip install -q Pillow
  - IDJANGO=$(./travis.py $DJANGO)
  - pip install -q $IDJANGO
  - pip install -e .
  - pip install -q coveralls tox-travis

before_script:
  # - mysql -e 'create database test;' -u root
  - mysql -e 'create database taskorganizer;' -u root
  - psql -c 'create database taskorganizer;' -U admin

script:
  # - python manage.py test tests/ --pattern="tests_*.py"
  # - django-admin.py --version
  - tox
  - coverage run --source=tasklist -m ./tests/test_*
  # - coverage report -m

after_success:
  - coveralls

deploy:
  provider: pages
  local_dir: "./"
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: 
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change